server:
    port: 8082

spring:
    datasource:
        #driver-class-name: com.mysql.jdbc.Driver
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/seckill_test?serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: root

    redis:
        host: localhost
        port: 6379
        database: 0
        password: 123456

rocketmq:
    name-server: 192.168.100.128:9876

mybatis:
    mapper-locations: classpath:mapper/*.xml
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
